### ISSUE TITLE
Using SCIP with IPOPT/LAPACK/Cplex

### ISSUE THREAD

**Issue by sbebo** [ryanjoneil/SCIP.jl#25]
I was working on the interface for quadratic programming. I tried to run the MBP tests, and I realized my scipopt library was not compiled against Ipopt: SCIP relies on Ipopt for LAPACK, so without it it's unable to check if the quadratic form is positive, a pretty big limitation. 
This results in SCIP treating any problem as nonconvex, which is clearly not ideal (I haven't even waited till completion of the first test problem, it seemed to take ages).

Compiling SCIP with "IPOPT=true IOPTOPT=opt", I get a library with some undefined Ipopt symbols, that can't be used with SCIP.jl. (Same issue compiling with LPS=cpx).

I tried this on OSX, on which I don't have much experience building stuff, and on linux. Same problem.
Ideas?

**Comment by mlubin** [comment]
Would definitely be cool to have quadratic (and nonlinear) problems working through SCIP, though I haven't tried building SCIP with Ipopt before. Maybe better question for a SCIP support forum? @fserra?

**Comment by fserra** [comment]
hey guys
I have no idea what the problem is when compiling with Ipopt... So what is
the issue exactly?

**Comment by svigerske** [comment]
Probably, there is a confusion because the SCIP library does not include the Ipopt (or Cplex) libraries as dependencies. You might need another step to build a shared library that has SCIP and all its dependencies included. Also, for SCIP the default is to build a static library, while you could enable a shared library via SHARED=true. But also in the latter case, I'm not sure that these libs will always know (list via ldd) all their dependencies. It's like with COIN-OR before the recent transitation that made --enable-dependency-linking (or something similar) the default.

**Comment by sbebo** [comment]
Yes, that's what I thought. I did try to use --enable-dependency-linking, to no avail -- I admit I didn't try really hard though.

**Comment by mlubin** [comment]
If the scip library doesn't properly list its dependencies, you'll have to ``dlopen`` the ipopt library with ``RTLD_GLOBAL`` before using scip. See [here](https://github.com/JuliaOpt/SCS.jl/blob/da189d88f8af70417337351c969861adb42cf75d/src/SCS.jl#L17) for an example

**Comment by sbebo** [comment]
Cool, for Ipopt 
```julia
@unix_only dlopen("libipopt", RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
```
does the job. For Cplex things seem to be a bit more complicated (the binary lists a bunch of additional dependencies that seem to be system dependent).
